- name: Demo playbook
  hosts: all
  tasks:
<<<<<<< HEAD
    -name: print Hello World
     ansible.builtin.debug:
=======
     -name: print Hello World
      ansible.builtin.debug:
>>>>>>> origin/main
       msg: Hello World


